Repository google/site-kit-wp, pull requests merged in 2019-06, with the labels that each got.

#15 Removes babel-plugin-makepot package from the build process
  .babelrc
  package-lock.json
  package.json
  webpack.config.js
Labels: Bug, P0

#46 Test oldest supported WP version, automate latest WP version, include…
  .travis.yml
  tests/bin/install-wp-tests.sh
Labels: Bug, P0

#32 Check for encryption constant before use it
  includes/Core/Storage/Data_Encryption.php
Labels: Bug, P1

#42 Composer: Require `wordpress/core-implementation` and put `johnpbloch/wordpress-core` into `require-dev`
  composer.json
Labels: Bug, P1

#22 Ensure domain sent for reporting is consistent
  assets/js/util/index.js
Labels: Bug, P1

#64 fix console error innerHTML of null on iframe existing tag check
  assets/js/util/index.js
Labels: Bug
